=== GoiToLaTri/xml_va_ungdung/buoi_4/b4_student_manage.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="dssv">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ds_sinhvien">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="sinhvien" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="mssv" type="xs:string"/>
                                        <xs:element name="hoten" type="xs:string"/>
                                        <xs:element name="email" type="xs:string"/>
                                        <xs:element name="diachi" type="xs:string"/>
                                        <xs:element name="sdt" type="xs:string"/>
                                        <xs:element name="lop" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>

                    <xs:key name="studentKey">
                        <xs:selector xpath="sinhvien"/>
                        <xs:field xpath="mssv"/>
                    </xs:key>

                    <xs:keyref name="studentClassRef" refer="classKey">
                        <xs:selector xpath="sinhvien"/>
                        <xs:field xpath="lop"/>
                    </xs:keyref>
                </xs:element>

                <xs:element name="ds_lop">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="lop" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ma" type="xs:string"/>
                                        <xs:element name="ten" type="xs:string"/>
                                        <xs:element name="khoa" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>

                   <xs:key name="classKey">
                        <xs:selector xpath="lop"/>
                        <xs:field xpath="ma"/>
                    </xs:key>

                    <xs:keyref name="classDepartmentRef" refer="departmentKey">
                        <xs:selector xpath="lop"/>
                        <xs:field xpath="khoa"/>
                    </xs:keyref>
                </xs:element>

                <xs:element name="ds_khoa">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="khoa" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="ma" type="xs:string"/>
                                        <xs:element name="ten" type="xs:string"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                        <xs:key name="departmentKey">
                            <xs:selector xpath="khoa"/>
                            <xs:field xpath="ma"/>
                        </xs:key>
                </xs:element>

            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== GoiToLaTri/xml_va_ungdung/buoi_4/student_manage.xml
<?xml version="1.0" encoding="UTF-8"?>

<dssv xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
     xsi:noNamespaceSchemaLocation="../buoi_3/b4_student_manage.xsd">
     <ds_sinhvien>
        <sinhvien>
            <mssv>SV001</mssv>
            <hoten>Nguyen Van A</hoten>
            <email>nva@gmail.com</email>
            <diachi>Can Tho</diachi>
            <sdt>+84999966666</sdt>
            <lop>CTK42</lop>
        </sinhvien>

        <sinhvien>
            <mssv>SV002</mssv>
            <hoten>Tran Thi B</hoten>
            <email>ttb@gmail.com</email>
            <diachi>Can Tho</diachi>
            <sdt>+84999966666</sdt>
            <lop>CTK42</lop>
        </sinhvien>
     </ds_sinhvien>

     <ds_lop>
        <lop>
            <ma>L01</ma>
            <ten>CTK42</ten>
            <khoa>KHOA01</khoa>
        </lop>

        <lop>
            <ma>L02</ma>
            <ten>CTK43</ten>
            <khoa>KHOA02</khoa>
        </lop>
     </ds_lop>

     <ds_khoa>
        <khoa>
            <ma>KHOA01</ma>
            <ten>KTPM</ten>
        </khoa>

        <khoa>
            <ma>KHOA02</ma>
            <ten>KTMT</ten>
        </khoa>

        <khoa>
            <ma>KHOA03</ma>
            <ten>KHMT</ten>
        </khoa>

        <khoa>
            <ma>KHOA04</ma>
            <ten>KTW</ten>
        </khoa>
    </ds_khoa>
</dssv>
