=== GoiToLaTri/xml_va_ungdung/buoi_2/b1_nhansu.dtd
<!ELEMENT congty (dep:phongban+)>

<!ATTLIST congty
    xmlns:hr CDATA #REQUIRED 
	xmlns:dep CDATA #REQUIRED
>

<!ELEMENT dep:phongban (hr:nhanvien+)>
<!ATTLIST dep:phongban
    ten CDATA #REQUIRED
>

<!ELEMENT hr:nhanvien (hr:name, hr:position)>
<!ATTLIST hr:nhanvien
    id ID #REQUIRED
>

<!ELEMENT hr:name (#PCDATA)>
<!ELEMENT hr:position (#PCDATA)>

=== GoiToLaTri/xml_va_ungdung/buoi_1/nhansu.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE congty SYSTEM "/buoi_2/b1_nhansu.dtd">

<congty xmlns:hr="http://company.com/hr"
        xmlns:dep="http://company.com/department">

    <dep:phongban ten="Phòng Kế Toán">
        <hr:nhanvien id="NV001">
            <hr:name>Nguyễn Văn A</hr:name>
            <hr:position>Kế toán trưởng</hr:position>
        </hr:nhanvien>
        <hr:nhanvien id="NV002">
            <hr:name>Trần Thị B</hr:name>
            <hr:position>Nhân viên kế toán</hr:position>
        </hr:nhanvien>
    </dep:phongban>

    <dep:phongban ten="Phòng IT">
        <hr:nhanvien id="NV003">
            <hr:name>Lê Văn C</hr:name>
            <hr:position>Lập trình viên</hr:position>
        </hr:nhanvien>
    </dep:phongban>

</congty>
